apiVersion: v1
kind: Service
metadata:
  namespace: reposyncer-test
  name: reposyncer-test-backend
  labels:
    k8s-app: reposyncer-test-backend
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    k8s-app: reposyncer-test-backend
